kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: web-dev-web-access
  namespace: web
subjects:
- kind: User
  name: web-dev
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: edit-web-access
  apiGroup: rbac.authorization.k8s.io
  namespace: web
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: web-dev-api-access
  namespace: api
subjects:
- kind: User
  name: web-dev
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: view-api-access
  apiGroup: rbac.authorization.k8s.io
  namespace: api

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: api-dev-web-access
  namespace: web
subjects:
- kind: User
  name: api-dev
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: view-web-access
  apiGroup: rbac.authorization.k8s.io
  namespace: web
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: api-dev-api-access
  namespace: api
subjects:
- kind: User
  name: api-dev
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: edit-api-access
  apiGroup: rbac.authorization.k8s.io
  namespace: api
